# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Amluto.Steps
PackageVersion: 1.0.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/amluto-solutions/steps/releases/download/v1.0.0/amluto-steps-1.0.0-x64-setup.exe
  InstallerSha256: D071F8C6D52ECD108141E0EC1A31DF2BE0368B738F18BFC09A512CC66E48A888
  ProductCode: Steps
  AppsAndFeaturesEntries:
  - DisplayName: Steps
    Publisher: Amluto Solutions Ltd
    ProductCode: Steps
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/amluto-solutions/steps/releases/download/v1.0.0/amluto-steps-1.0.0-x64.msi
  InstallerSha256: 74559917C838A537060D5A9C73BA9F2BEC4D96C48D6195172CED8A39E619B7D8
  ProductCode: '{F53D0FB3-FBBB-4E26-9F7D-74D7D18A7D99}'
  AppsAndFeaturesEntries:
  - DisplayName: Steps
    Publisher: Amluto Solutions Ltd
    ProductCode: '{F53D0FB3-FBBB-4E26-9F7D-74D7D18A7D99}'
    UpgradeCode: '{A8772EA5-E41C-5D68-862D-0BE9828A10A7}'
ManifestType: installer
ManifestVersion: 1.10.0
ReleaseDate: 2026-10-02
